artifacts_root: artifacts

#sab kch components ye sb artifacts folder me rhega
#path/url ye sb store krana h toh config.yaml me store krate

#data_ingestion ke andar data download krege

data_ingestion:
   root_dir: artifacts/data_ingestion
   source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
   local_data_file: artifacts/data_ingestion/data.zip
   unzip_dir: artifacts/data_ingestion

data_validation:
   root_dir: artifacts/data_validation
   STATUS_FILE: artifacts/data_validation/status.txt
   ALL_REQUIRED_FILES: ["train","test","validation"]  #basically check kr rhe ki ye sari files present h ya ni